import React from 'react';
import { Container } from '../ui/Container';
import type { ClientConfig } from '../../types/config';
import { DynamicIcon } from '../ui/DynamicIcon';
import { ArrowLeft } from 'lucide-react';

interface FooterProps {
  config: ClientConfig;
}

export const Footer: React.FC<FooterProps> = ({ config }) => {
  const { brand, contact } = config;
  const currentYear = new Date().getFullYear();

  return (
    <footer className="border-t border-slate-850/80 bg-themeBg/90 py-12 text-slate-400">
      <Container>
        <div className="grid grid-cols-1 md:grid-cols-4 gap-8 mb-12">
          {/* Brand Col */}
          <div className="md:col-span-2 space-y-4">
            <h3 className="text-xl font-bold font-outfit text-themeText tracking-tight">
              {brand.name}
            </h3>
            <p className="text-sm text-slate-400 max-w-md leading-relaxed">
              {brand.tagline}
            </p>
            <div className="flex items-center gap-2 text-xs text-slate-500">
              <span className="inline-block h-2 w-2 rounded-full bg-emerald-400" />
              <span>Modular Configuration Architecture v1.0</span>
            </div>
          </div>

          {/* Quick Links */}
          <div className="space-y-3">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200">
              Navigation
            </h4>
            <ul className="space-y-2 text-sm">
              <li>
                <a href="#offerings" className="hover:text-themeAccent transition-colors">
                  Core Offerings
                </a>
              </li>
              <li>
                <a href="#about" className="hover:text-themeAccent transition-colors">
                  Company & Team
                </a>
              </li>
              <li>
                <a href="#social-proof" className="hover:text-themeAccent transition-colors">
                  Testimonials
                </a>
              </li>
              <li>
                <a href="#contact" className="hover:text-themeAccent transition-colors">
                  Get in Touch
                </a>
              </li>
            </ul>
          </div>

          {/* Social Profiles */}
          <div className="space-y-3">
            <h4 className="text-xs font-semibold uppercase tracking-wider text-slate-200">
              Connect
            </h4>
            {contact?.socialLinks && Object.keys(contact.socialLinks).length > 0 ? (
              <div className="flex flex-col space-y-2 text-sm">
                {Object.entries(contact.socialLinks).map(([name, url]) => (
                  <a
                    key={name}
                    href={url}
                    target="_blank"
                    rel="noopener noreferrer"
                    className="flex items-center gap-2 hover:text-themeAccent transition-colors"
                  >
                    <DynamicIcon name={name.toLowerCase().includes('git') ? 'Github' : name.toLowerCase().includes('link') ? 'Linkedin' : 'Globe'} className="w-4 h-4 text-themeAccent" />
                    <span>{name}</span>
                  </a>
                ))}
              </div>
            ) : (
              <p className="text-xs text-slate-500">Direct inquiries welcome via contact form.</p>
            )}
          </div>
        </div>

        {/* Portal Backlink Banner */}
        <div className="mb-8 p-4 sm:p-5 rounded-2xl border border-indigo-500/20 bg-indigo-950/20 backdrop-blur-sm flex flex-col sm:flex-row items-center justify-between gap-4 text-xs">
          <div className="flex items-center gap-2.5 text-indigo-300 text-center sm:text-left">
            <span className="relative flex h-2.5 w-2.5 shrink-0">
              <span className="animate-ping absolute inline-flex h-full w-full rounded-full bg-indigo-400 opacity-75"></span>
              <span className="relative inline-flex rounded-full h-2.5 w-2.5 bg-indigo-500"></span>
            </span>
            <span>You are previewing a client site generated by the HyperLaunch Web Builder Engine.</span>
          </div>
          <a
            href="/"
            className="inline-flex items-center gap-2 px-4 py-2 rounded-xl bg-indigo-600 hover:bg-indigo-500 text-white font-semibold transition-all shadow-md shadow-indigo-600/20 shrink-0 hover:scale-[1.02] active:scale-[0.98]"
          >
            <ArrowLeft className="w-3.5 h-3.5" />
            <span>Return to Landing Portal</span>
          </a>
        </div>

        {/* Bottom Bar */}
        <div className="pt-8 border-t border-slate-800/80 flex flex-col sm:flex-row items-center justify-between gap-4 text-xs text-slate-500">
          <p>© {currentYear} {brand.name}. All rights reserved.</p>
          <div className="flex items-center gap-6">
            <span className="hover:text-slate-400 cursor-pointer">Privacy Policy</span>
            <span>•</span>
            <span className="hover:text-slate-400 cursor-pointer">Terms of Service</span>
            <span>•</span>
            <span className="hover:text-slate-400 cursor-pointer">Security</span>
          </div>
        </div>
      </Container>
    </footer>
  );
};
